name: Deploy Laravel to InfinityFree

on:
  push:
    branches:
      - main   # change if you deploy from another branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: mbstring, curl, xml, bcmath, gd

    # 3. Install Composer dependencies
    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    # 4. Setup Node.js (for Vite)
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # 5. Install npm packages
    - name: Install NPM dependencies
      run: npm install

    # 6. Build production assets
    - name: Build Vite assets
      run: npm run build

    # 7. Deploy to InfinityFree via FTP
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./          # deploy everything in repo root
        server-dir: ${{ secrets.FTP_DIR }}
        git-ftp-args: --insecure
